import type { AiModel } from "@/types/landing";

type DummyModel = Omit<AiModel, "provider_logo_url" | "status" | "deprecation_notice" | "prices"> & {
  inputUsd: number;
  outputUsd: number;
};

const USD_TO_IDR = 16_500;

const catalog: DummyModel[] = [
  {
    id: "demo-openai-gpt-4o",
    model_id: "gpt-4o",
    display_name: "GPT-4o",
    description: "Model multimodal serbaguna untuk teks, gambar, dan otomasi.",
    provider_name: "OpenAI",
    provider_slug: "openai",
    category: "chat",
    context_window: 128_000,
    max_output_tokens: 16_384,
    supports_streaming: true,
    supports_vision: true,
    supports_function_calling: true,
    supports_json_mode: true,
    is_featured: true,
    sort_order: 1,
    inputUsd: 2.5,
    outputUsd: 10,
  },
  {
    id: "demo-openai-gpt-4o-mini",
    model_id: "gpt-4o-mini",
    display_name: "GPT-4o Mini",
    description: "Model cepat dan hemat untuk aplikasi dengan volume tinggi.",
    provider_name: "OpenAI",
    provider_slug: "openai",
    category: "chat",
    context_window: 128_000,
    max_output_tokens: 16_384,
    supports_streaming: true,
    supports_vision: true,
    supports_function_calling: true,
    supports_json_mode: true,
    is_featured: false,
    sort_order: 2,
    inputUsd: 0.15,
    outputUsd: 0.6,
  },
  {
    id: "demo-openai-o3",
    model_id: "o3",
    display_name: "o3",
    description: "Model reasoning untuk analisis kompleks dan pemecahan masalah.",
    provider_name: "OpenAI",
    provider_slug: "openai",
    category: "reasoning",
    context_window: 200_000,
    max_output_tokens: 100_000,
    supports_streaming: true,
    supports_vision: true,
    supports_function_calling: true,
    supports_json_mode: true,
    is_featured: true,
    sort_order: 3,
    inputUsd: 2,
    outputUsd: 8,
  },
  {
    id: "demo-anthropic-claude-sonnet-4",
    model_id: "claude-sonnet-4-20250514",
    display_name: "Claude Sonnet 4",
    description: "Keseimbangan performa dan kecepatan untuk coding serta agen AI.",
    provider_name: "Anthropic",
    provider_slug: "anthropic",
    category: "chat",
    context_window: 200_000,
    max_output_tokens: 16_000,
    supports_streaming: true,
    supports_vision: true,
    supports_function_calling: true,
    supports_json_mode: true,
    is_featured: true,
    sort_order: 4,
    inputUsd: 3,
    outputUsd: 15,
  },
  {
    id: "demo-anthropic-claude-haiku",
    model_id: "claude-3-5-haiku-20241022",
    display_name: "Claude 3.5 Haiku",
    description: "Respons cepat untuk chatbot, klasifikasi, dan pemrosesan dokumen.",
    provider_name: "Anthropic",
    provider_slug: "anthropic",
    category: "chat",
    context_window: 200_000,
    max_output_tokens: 8_192,
    supports_streaming: true,
    supports_vision: true,
    supports_function_calling: true,
    supports_json_mode: true,
    is_featured: false,
    sort_order: 5,
    inputUsd: 0.8,
    outputUsd: 4,
  },
  {
    id: "demo-google-gemini-pro",
    model_id: "gemini-2.5-pro",
    display_name: "Gemini 2.5 Pro",
    description: "Model multimodal dengan context panjang untuk tugas kompleks.",
    provider_name: "Google",
    provider_slug: "google",
    category: "chat",
    context_window: 1_048_576,
    max_output_tokens: 65_536,
    supports_streaming: true,
    supports_vision: true,
    supports_function_calling: true,
    supports_json_mode: true,
    is_featured: true,
    sort_order: 6,
    inputUsd: 1.25,
    outputUsd: 10,
  },
  {
    id: "demo-google-gemini-flash",
    model_id: "gemini-2.5-flash",
    display_name: "Gemini 2.5 Flash",
    description: "Model multimodal berlatensi rendah untuk aplikasi real-time.",
    provider_name: "Google",
    provider_slug: "google",
    category: "chat",
    context_window: 1_048_576,
    max_output_tokens: 65_536,
    supports_streaming: true,
    supports_vision: true,
    supports_function_calling: true,
    supports_json_mode: true,
    is_featured: false,
    sort_order: 7,
    inputUsd: 0.15,
    outputUsd: 0.6,
  },
  {
    id: "demo-meta-llama-70b",
    model_id: "llama-3.3-70b-versatile",
    display_name: "Llama 3.3 70B",
    description: "Model open-weight untuk percakapan dan generasi konten.",
    provider_name: "Meta",
    provider_slug: "meta",
    category: "chat",
    context_window: 128_000,
    max_output_tokens: 32_768,
    supports_streaming: true,
    supports_vision: false,
    supports_function_calling: true,
    supports_json_mode: true,
    is_featured: false,
    sort_order: 8,
    inputUsd: 0.59,
    outputUsd: 0.79,
  },
  {
    id: "demo-mistral-large",
    model_id: "mistral-large-latest",
    display_name: "Mistral Large",
    description: "Model multilingual untuk reasoning, coding, dan function calling.",
    provider_name: "Mistral AI",
    provider_slug: "mistral",
    category: "chat",
    context_window: 128_000,
    max_output_tokens: 8_192,
    supports_streaming: true,
    supports_vision: false,
    supports_function_calling: true,
    supports_json_mode: true,
    is_featured: false,
    sort_order: 9,
    inputUsd: 2,
    outputUsd: 6,
  },
  {
    id: "demo-deepseek-r1",
    model_id: "deepseek-r1",
    display_name: "DeepSeek R1",
    description: "Model reasoning untuk matematika, sains, dan coding tingkat lanjut.",
    provider_name: "DeepSeek",
    provider_slug: "deepseek",
    category: "reasoning",
    context_window: 128_000,
    max_output_tokens: 16_384,
    supports_streaming: true,
    supports_vision: false,
    supports_function_calling: false,
    supports_json_mode: true,
    is_featured: true,
    sort_order: 10,
    inputUsd: 0.55,
    outputUsd: 2.19,
  },
  {
    id: "demo-openai-embedding-small",
    model_id: "text-embedding-3-small",
    display_name: "Text Embedding 3 Small",
    description: "Embedding ekonomis untuk pencarian semantik dan RAG.",
    provider_name: "OpenAI",
    provider_slug: "openai",
    category: "embedding",
    context_window: 8_191,
    max_output_tokens: null,
    supports_streaming: false,
    supports_vision: false,
    supports_function_calling: false,
    supports_json_mode: false,
    is_featured: false,
    sort_order: 11,
    inputUsd: 0.02,
    outputUsd: 0,
  },
  {
    id: "demo-openai-embedding-large",
    model_id: "text-embedding-3-large",
    display_name: "Text Embedding 3 Large",
    description: "Embedding akurasi tinggi untuk retrieval dan rekomendasi.",
    provider_name: "OpenAI",
    provider_slug: "openai",
    category: "embedding",
    context_window: 8_191,
    max_output_tokens: null,
    supports_streaming: false,
    supports_vision: false,
    supports_function_calling: false,
    supports_json_mode: false,
    is_featured: false,
    sort_order: 12,
    inputUsd: 0.13,
    outputUsd: 0,
  },
];

export const dummyAiModels: AiModel[] = catalog.map(({ inputUsd, outputUsd, ...model }) => ({
  ...model,
  provider_logo_url: null,
  status: "active",
  deprecation_notice: null,
  prices: [
    {
      currency_code: "IDR",
      input_price_per_1m: Math.round(inputUsd * USD_TO_IDR),
      output_price_per_1m: Math.round(outputUsd * USD_TO_IDR),
    },
    {
      currency_code: "USD",
      input_price_per_1m: inputUsd,
      output_price_per_1m: outputUsd,
    },
  ],
}));
